import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Nunito } from "next/font/google";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link type="text/css" rel="stylesheet" href="css/lightgallery.css" />
        <link type="text/css" rel="stylesheet" href="css/lg-zoom.css" />
        <link type="text/css" rel="stylesheet" href="css/lg-thumbnail.css" />
        <link
          type="text/css"
          rel="stylesheet"
          href="css/lightgallery-bundle.css"
        />
      </head>
      <body className={`${nunito.className}, ${manrope.className}`}>
        {children}
      </body>
    </html>
  );
}
